name: Cross-compilation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Build for ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-name: Linux aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
          - os-name: Windows x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-gnu
          - os-name: macOS x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rusty-Man Computer for ${{ matrix.platform.os-name }}
          path: |
            ./target/${{ matrix.platform.target }}/release/rusty_man_computer*
            ./target/${{ matrix.platform.target }}/release/bin_creator*
            !**/*.d
          if-no-files-found: error
